 version: '3'
 services:
   jenkins:
     build: .
     privileged: true
     user: root
     ports:
       - 8080:8080
     volumes:
       - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock
     restart: always
